// GENERATED by firmware/tools/gen_physical.py — do not edit.
// Source: spec/physical-schema.json (schema 1, sha256:44128efbe8ef58576acbde99bc3de9027fb551c599a36fccecfe9afe061b1c01)

export const PHYSICAL_VERSION = 1 as const;
export const PHYSICAL_SCHEMA_DIGEST = "sha256:44128efbe8ef58576acbde99bc3de9027fb551c599a36fccecfe9afe061b1c01" as const;

export interface PhysicalParams {
  innerRadiusMm: number;
  wallThicknessMm: number;
  liquidIor: number;
  wallIor: number;
  absorptionR: number;
  absorptionG: number;
  absorptionB: number;
  lightAngleDeg: number;
  lightSizeDeg: number;
  lightIntensity: number;
  ambientIntensity: number;
  backingReflectance: number;
  marksReflectance: number;
  exposure: number;
  hoursY: number;
  minutesY: number;
}

export interface PhysicalParamsEnvelope {
  readonly version: typeof PHYSICAL_VERSION;
  readonly params: PhysicalParams;
}

export interface PhysicalFieldMeta {
  readonly key: keyof PhysicalParams;
  readonly label: string;
  readonly unit: string;
  readonly min: number;
  readonly max: number;
  readonly step: number;
  readonly group: string;
  readonly help: string;
  readonly integer: boolean;
}

export type PhysicalMeta = PhysicalFieldMeta;

export const DEFAULT_PHYSICAL_PARAMS: PhysicalParams = {
  innerRadiusMm: 2.55,
  wallThicknessMm: 0.45,
  liquidIor: 1.47,
  wallIor: 1.49,
  absorptionR: 0.09,
  absorptionG: 0.12,
  absorptionB: 0.8,
  lightAngleDeg: -35,
  lightSizeDeg: 30,
  lightIntensity: 2,
  ambientIntensity: 0.15,
  backingReflectance: 0.35,
  marksReflectance: 0.85,
  exposure: 1,
  hoursY: 0,
  minutesY: 168,
};

export const PHYSICAL_META: readonly PhysicalFieldMeta[] = [
  { key: "innerRadiusMm", label: "Inner radius", unit: "mm", min: 0.5, max: 3, step: 0.05, group: "Vessel", help: "Radius of the liquid-facing vessel surface.", integer: false },
  { key: "wallThicknessMm", label: "Wall thickness", unit: "mm", min: 0.05, max: 1, step: 0.05, group: "Vessel", help: "Thickness of the glass or acrylic wall around the liquid.", integer: false },
  { key: "liquidIor", label: "Liquid refractive index", unit: "IOR", min: 1, max: 1.7, step: 0.005, group: "Liquid", help: "Refractive index used at the liquid interfaces.", integer: false },
  { key: "wallIor", label: "Wall refractive index", unit: "IOR", min: 1, max: 1.7, step: 0.005, group: "Vessel", help: "Refractive index of the vessel wall material.", integer: false },
  { key: "absorptionR", label: "Absorption red", unit: "1/mm", min: 0, max: 3, step: 0.01, group: "Liquid", help: "Beer-Lambert absorption coefficient for the red channel.", integer: false },
  { key: "absorptionG", label: "Absorption green", unit: "1/mm", min: 0, max: 3, step: 0.01, group: "Liquid", help: "Beer-Lambert absorption coefficient for the green channel.", integer: false },
  { key: "absorptionB", label: "Absorption blue", unit: "1/mm", min: 0, max: 3, step: 0.01, group: "Liquid", help: "Beer-Lambert absorption coefficient for the blue channel.", integer: false },
  { key: "lightAngleDeg", label: "Light angle", unit: "deg", min: -85, max: 85, step: 1, group: "Lighting", help: "Direction of the area light in the renderer view.", integer: false },
  { key: "lightSizeDeg", label: "Light size", unit: "deg", min: 5, max: 90, step: 1, group: "Lighting", help: "Angular size of the area light source.", integer: false },
  { key: "lightIntensity", label: "Light intensity", unit: "relative", min: 0, max: 5, step: 0.05, group: "Lighting", help: "Intensity multiplier for the area light.", integer: false },
  { key: "ambientIntensity", label: "Ambient intensity", unit: "relative", min: 0, max: 2, step: 0.01, group: "Lighting", help: "Uniform environment fill before material attenuation.", integer: false },
  { key: "backingReflectance", label: "Backing reflectance", unit: "relative", min: 0, max: 1, step: 0.01, group: "Backing", help: "Diffuse reflectance of the surface behind the vessel.", integer: false },
  { key: "marksReflectance", label: "Marks reflectance", unit: "relative", min: 0, max: 1, step: 0.01, group: "Backing", help: "Reflectance of rear marks and tick surfaces.", integer: false },
  { key: "exposure", label: "Exposure", unit: "stops", min: 0.1, max: 3, step: 0.05, group: "Display", help: "Display exposure applied after linear optical compositing.", integer: false },
  { key: "hoursY", label: "Hours layout Y", unit: "px", min: 0, max: 236, step: 1, group: "Layout", help: "Top pixel coordinate of the hours tube.", integer: true },
  { key: "minutesY", label: "Minutes layout Y", unit: "px", min: 0, max: 236, step: 1, group: "Layout", help: "Top pixel coordinate of the minutes tube.", integer: true },
] as const;

const PHYSICAL_KEYS = ["innerRadiusMm","wallThicknessMm","liquidIor","wallIor","absorptionR","absorptionG","absorptionB","lightAngleDeg","lightSizeDeg","lightIntensity","ambientIntensity","backingReflectance","marksReflectance","exposure","hoursY","minutesY"] as const;

export const PHYSICAL_FIELD_NAMES: readonly string[] = PHYSICAL_KEYS;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isKnownKey(key: string): key is keyof PhysicalParams {
  return (PHYSICAL_KEYS as readonly string[]).includes(key);
}

function invalid(message: string): never {
  throw new Error(`Invalid physical parameters: ${message}`);
}

/** Validate a complete, versionless PhysicalParams object. */
export function validatePhysicalParams(value: unknown): PhysicalParams {
  if (!isRecord(value)) invalid("expected an object");
  const keys = Object.keys(value);
  if (keys.length !== PHYSICAL_KEYS.length || keys.some((key) => !isKnownKey(key))) {
    invalid("expected exactly the known fields");
  }
  const result = {} as PhysicalParams;
  for (const meta of PHYSICAL_META) {
    const raw = value[meta.key];
    if (typeof raw !== "number" || !Number.isFinite(raw)) invalid(`${meta.key} must be finite`);
    if (raw < meta.min || raw > meta.max) invalid(`${meta.key} must be in [${meta.min}, ${meta.max}]`);
    if (meta.integer && !Number.isInteger(raw)) invalid(`${meta.key} must be an integer`);
    result[meta.key] = raw;
  }
  if (result.innerRadiusMm + result.wallThicknessMm > 3.32) {
    invalid("innerRadiusMm + wallThicknessMm must be at most 3.32 mm");
  }
  const height = Math.round((2 * (result.innerRadiusMm + result.wallThicknessMm)) / 0.083);
  if (height < 4 || height > 80) invalid("derived tube height must be in [4, 80] px");
  if (result.hoursY + height > 240 || result.minutesY + height > 240) {
    invalid("layout Y plus derived tube height must be at most 240 px");
  }
  if (result.hoursY < result.minutesY + height && result.minutesY < result.hoursY + height) {
    invalid("hours and minutes tube strips must not overlap");
  }
  return result;
}
