// GENERATED by firmware/tools/gen_physical.py — do not edit.
// Source: spec/physical-schema.json (schema 1, sha256:44128efbe8ef58576acbde99bc3de9027fb551c599a36fccecfe9afe061b1c01)
#pragma once

#include <cmath>
#include <cstddef>
#include <cstring>

namespace physical {

constexpr int PHYSICAL_VERSION = 1;
constexpr const char *PHYSICAL_SCHEMA_DIGEST = "sha256:44128efbe8ef58576acbde99bc3de9027fb551c599a36fccecfe9afe061b1c01";

struct Params {
  float innerRadiusMm;
  float wallThicknessMm;
  float liquidIor;
  float wallIor;
  float absorptionR;
  float absorptionG;
  float absorptionB;
  float lightAngleDeg;
  float lightSizeDeg;
  float lightIntensity;
  float ambientIntensity;
  float backingReflectance;
  float marksReflectance;
  float exposure;
  float hoursY;
  float minutesY;
};

struct Field {
  const char *name;
  float Params::*member;
  float min;
  float max;
  bool integer;
};

constexpr Field FIELDS[] = {
  {"innerRadiusMm", &Params::innerRadiusMm, 0.5f, 3.0f, false},
  {"wallThicknessMm", &Params::wallThicknessMm, 0.05f, 1.0f, false},
  {"liquidIor", &Params::liquidIor, 1.0f, 1.7f, false},
  {"wallIor", &Params::wallIor, 1.0f, 1.7f, false},
  {"absorptionR", &Params::absorptionR, 0.0f, 3.0f, false},
  {"absorptionG", &Params::absorptionG, 0.0f, 3.0f, false},
  {"absorptionB", &Params::absorptionB, 0.0f, 3.0f, false},
  {"lightAngleDeg", &Params::lightAngleDeg, -85.0f, 85.0f, false},
  {"lightSizeDeg", &Params::lightSizeDeg, 5.0f, 90.0f, false},
  {"lightIntensity", &Params::lightIntensity, 0.0f, 5.0f, false},
  {"ambientIntensity", &Params::ambientIntensity, 0.0f, 2.0f, false},
  {"backingReflectance", &Params::backingReflectance, 0.0f, 1.0f, false},
  {"marksReflectance", &Params::marksReflectance, 0.0f, 1.0f, false},
  {"exposure", &Params::exposure, 0.1f, 3.0f, false},
  {"hoursY", &Params::hoursY, 0.0f, 236.0f, true},
  {"minutesY", &Params::minutesY, 0.0f, 236.0f, true},
};
constexpr std::size_t FIELD_COUNT = sizeof(FIELDS) / sizeof(FIELDS[0]);

constexpr const char *FIELD_NAMES[] = {
  "innerRadiusMm",
  "wallThicknessMm",
  "liquidIor",
  "wallIor",
  "absorptionR",
  "absorptionG",
  "absorptionB",
  "lightAngleDeg",
  "lightSizeDeg",
  "lightIntensity",
  "ambientIntensity",
  "backingReflectance",
  "marksReflectance",
  "exposure",
  "hoursY",
  "minutesY",
};
constexpr std::size_t FIELD_NAME_COUNT = sizeof(FIELD_NAMES) / sizeof(FIELD_NAMES[0]);

inline Params defaults() {
  return Params{
    2.55f, // innerRadiusMm
    0.45f, // wallThicknessMm
    1.47f, // liquidIor
    1.49f, // wallIor
    0.09f, // absorptionR
    0.12f, // absorptionG
    0.8f, // absorptionB
    -35.0f, // lightAngleDeg
    30.0f, // lightSizeDeg
    2.0f, // lightIntensity
    0.15f, // ambientIntensity
    0.35f, // backingReflectance
    0.85f, // marksReflectance
    1.0f, // exposure
    0.0f, // hoursY
    168.0f, // minutesY
  };
}

inline bool validate(const Params &params) {
  for (std::size_t i = 0; i < FIELD_COUNT; ++i) {
    const Field &field = FIELDS[i];
    const float value = params.*(field.member);
    if (!std::isfinite(value) || value < field.min || value > field.max) return false;
    if (field.integer && std::floor(value) != value) return false;
  }
  if (params.innerRadiusMm + params.wallThicknessMm > 3.32f) return false;
  const int height = static_cast<int>(std::floor((2.0f * (params.innerRadiusMm + params.wallThicknessMm)) / 0.083f + 0.5f));
  if (height < 4 || height > 80) return false;
  if (params.hoursY + height > 240.0f || params.minutesY + height > 240.0f) return false;
  if (params.hoursY < params.minutesY + height && params.minutesY < params.hoursY + height) return false;
  return true;
}

inline bool setParam(Params &params, const char *name, float value) {
  if (name == nullptr || !std::isfinite(value)) return false;
  for (std::size_t i = 0; i < FIELD_COUNT; ++i) {
    const Field &field = FIELDS[i];
    if (std::strcmp(name, field.name) != 0) continue;
    Params candidate = params;
    candidate.*(field.member) = value;
    if (!validate(candidate)) return false;
    params = candidate;
    return true;
  }
  return false;
}

} // namespace physical
