#!/usr/bin/env python3
"""Generate the shared physical renderer model for TypeScript and C++.

The JSON file is the source of truth.  Normal invocation writes both generated
files; ``--check`` verifies that the checked-in files are deterministic outputs.
Only Python's standard library is used so the check also works on the firmware
build host.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = ROOT / "spec" / "physical-schema.json"
TS_PATH = ROOT / "sim" / "src" / "physical" / "model.ts"
CPP_PATH = ROOT / "firmware" / "src" / "physical" / "model.h"


def load_schema() -> tuple[dict[str, Any], list[dict[str, Any]], str]:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    if not isinstance(schema, dict):
        raise ValueError("physical schema must be an object")
    fields = schema.get("fields")
    if not isinstance(fields, list) or not fields:
        raise ValueError("physical schema must contain a non-empty fields array")
    keys: set[str] = set()
    required = ("key", "label", "unit", "default", "min", "max", "step", "group", "help")
    for field in fields:
        if not isinstance(field, dict) or any(name not in field for name in required):
            raise ValueError("each physical field needs key, label, unit, default, min, max, step, group, help")
        key = field["key"]
        if not isinstance(key, str) or not key or key in keys:
            raise ValueError(f"invalid or duplicate physical field key: {key!r}")
        keys.add(key)
        for name in ("default", "min", "max", "step"):
            value = field[name]
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValueError(f"{key}.{name} must be numeric")
        if field["min"] > field["max"] or not field["min"] <= field["default"] <= field["max"]:
            raise ValueError(f"invalid range/default for {key}")
        if field["step"] <= 0:
            raise ValueError(f"{key}.step must be positive")
        if field.get("integer", False) and any(float(field[name]) != int(field[name]) for name in ("default", "min", "max", "step")):
            raise ValueError(f"integer field {key} has a non-integer bound/default/step")

    version = schema.get("version")
    if isinstance(version, bool) or not isinstance(version, int) or version < 1:
        raise ValueError("physical schema version must be a positive integer")
    canonical = json.dumps(schema, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    digest = "sha256:" + hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    return schema, fields, digest


def js(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def number(value: Any) -> str:
    """Stable source spelling for a JSON numeric value."""
    if isinstance(value, int):
        return str(value)
    result = format(float(value), ".15g")
    if result == "-0":
        return "0"
    return result


def cpp_number(value: Any) -> str:
    result = number(value)
    if all(character not in result for character in ".eE"):
        result += ".0"
    return result + "f"


def generate_ts(schema: dict[str, Any], fields: list[dict[str, Any]], digest: str) -> str:
    version = schema["version"]
    keys = [field["key"] for field in fields]
    lines = [
        "// GENERATED by firmware/tools/gen_physical.py — do not edit.",
        f"// Source: spec/physical-schema.json (schema {version}, {digest})",
        "",
        f"export const PHYSICAL_VERSION = {version} as const;",
        f"export const PHYSICAL_SCHEMA_DIGEST = {js(digest)} as const;",
        "",
        "export interface PhysicalParams {",
    ]
    lines.extend(f"  {key}: number;" for key in keys)
    lines.extend(
        [
            "}",
            "",
            "export interface PhysicalParamsEnvelope {",
            "  readonly version: typeof PHYSICAL_VERSION;",
            "  readonly params: PhysicalParams;",
            "}",
            "",
            "export interface PhysicalFieldMeta {",
            "  readonly key: keyof PhysicalParams;",
            "  readonly label: string;",
            "  readonly unit: string;",
            "  readonly min: number;",
            "  readonly max: number;",
            "  readonly step: number;",
            "  readonly group: string;",
            "  readonly help: string;",
            "  readonly integer: boolean;",
            "}",
            "",
            "export type PhysicalMeta = PhysicalFieldMeta;",
            "",
            "export const DEFAULT_PHYSICAL_PARAMS: PhysicalParams = {",
        ]
    )
    lines.extend(f"  {field['key']}: {number(field['default'])}," for field in fields)
    lines.extend(["};", ""])
    lines.extend(
        [
            "export const PHYSICAL_META: readonly PhysicalFieldMeta[] = [",
        ]
    )
    for field in fields:
        lines.append(
            "  { key: %s, label: %s, unit: %s, min: %s, max: %s, step: %s, group: %s, help: %s, integer: %s },"
            % (
                js(field["key"]),
                js(field["label"]),
                js(field["unit"]),
                number(field["min"]),
                number(field["max"]),
                number(field["step"]),
                js(field["group"]),
                js(field["help"]),
                "true" if field.get("integer", False) else "false",
            )
        )
    lines.extend(["] as const;", "", f"const PHYSICAL_KEYS = {js(keys)} as const;", "", "export const PHYSICAL_FIELD_NAMES: readonly string[] = PHYSICAL_KEYS;", ""])
    lines.extend(
        [
            "function isRecord(value: unknown): value is Record<string, unknown> {",
            "  return typeof value === \"object\" && value !== null && !Array.isArray(value);",
            "}",
            "",
            "function isKnownKey(key: string): key is keyof PhysicalParams {",
            "  return (PHYSICAL_KEYS as readonly string[]).includes(key);",
            "}",
            "",
            "function invalid(message: string): never {",
            "  throw new Error(`Invalid physical parameters: ${message}`);",
            "}",
            "",
            "/** Validate a complete, versionless PhysicalParams object. */",
            "export function validatePhysicalParams(value: unknown): PhysicalParams {",
            "  if (!isRecord(value)) invalid(\"expected an object\");",
            "  const keys = Object.keys(value);",
            "  if (keys.length !== PHYSICAL_KEYS.length || keys.some((key) => !isKnownKey(key))) {",
            "    invalid(\"expected exactly the known fields\");",
            "  }",
            "  const result = {} as PhysicalParams;",
            "  for (const meta of PHYSICAL_META) {",
            "    const raw = value[meta.key];",
            "    if (typeof raw !== \"number\" || !Number.isFinite(raw)) invalid(`${meta.key} must be finite`);",
            "    if (raw < meta.min || raw > meta.max) invalid(`${meta.key} must be in [${meta.min}, ${meta.max}]`);",
            "    if (meta.integer && !Number.isInteger(raw)) invalid(`${meta.key} must be an integer`);",
            "    result[meta.key] = raw;",
            "  }",
            "  if (result.innerRadiusMm + result.wallThicknessMm > 3.32) {",
            "    invalid(\"innerRadiusMm + wallThicknessMm must be at most 3.32 mm\");",
            "  }",
            "  const height = Math.round((2 * (result.innerRadiusMm + result.wallThicknessMm)) / 0.083);",
            "  if (height < 4 || height > 80) invalid(\"derived tube height must be in [4, 80] px\");",
            "  if (result.hoursY + height > 240 || result.minutesY + height > 240) {",
            "    invalid(\"layout Y plus derived tube height must be at most 240 px\");",
            "  }",
            "  if (result.hoursY < result.minutesY + height && result.minutesY < result.hoursY + height) {",
            "    invalid(\"hours and minutes tube strips must not overlap\");",
            "  }",
            "  return result;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def generate_cpp(schema: dict[str, Any], fields: list[dict[str, Any]], digest: str) -> str:
    version = schema["version"]
    lines = [
        "// GENERATED by firmware/tools/gen_physical.py — do not edit.",
        f"// Source: spec/physical-schema.json (schema {version}, {digest})",
        "#pragma once",
        "",
        "#include <cmath>",
        "#include <cstddef>",
        "#include <cstring>",
        "",
        "namespace physical {",
        "",
        f"constexpr int PHYSICAL_VERSION = {version};",
        f"constexpr const char *PHYSICAL_SCHEMA_DIGEST = {js(digest)};",
        "",
        "struct Params {",
    ]
    lines.extend(f"  float {field['key']};" for field in fields)
    lines.extend(["};", "", "struct Field {", "  const char *name;", "  float Params::*member;", "  float min;", "  float max;", "  bool integer;", "};", ""])
    lines.append("constexpr Field FIELDS[] = {")
    for field in fields:
        lines.append(
            "  {%s, &Params::%s, %s, %s, %s},"
            % (
                js(field["key"]),
                field["key"],
                cpp_number(field["min"]),
                cpp_number(field["max"]),
                "true" if field.get("integer", False) else "false",
            )
        )
    lines.extend(["};", "constexpr std::size_t FIELD_COUNT = sizeof(FIELDS) / sizeof(FIELDS[0]);", ""])
    lines.append("constexpr const char *FIELD_NAMES[] = {")
    lines.extend(f"  {js(field['key'])}," for field in fields)
    lines.extend(
        [
            "};",
            "constexpr std::size_t FIELD_NAME_COUNT = sizeof(FIELD_NAMES) / sizeof(FIELD_NAMES[0]);",
            "",
            "inline Params defaults() {",
            "  return Params{",
        ]
    )
    lines.extend(f"    {cpp_number(field['default'])}, // {field['key']}" for field in fields)
    lines.extend(
        [
            "  };",
            "}",
            "",
            "inline bool validate(const Params &params) {",
            "  for (std::size_t i = 0; i < FIELD_COUNT; ++i) {",
            "    const Field &field = FIELDS[i];",
            "    const float value = params.*(field.member);",
            "    if (!std::isfinite(value) || value < field.min || value > field.max) return false;",
            "    if (field.integer && std::floor(value) != value) return false;",
            "  }",
            "  if (params.innerRadiusMm + params.wallThicknessMm > 3.32f) return false;",
            "  const int height = static_cast<int>(std::floor((2.0f * (params.innerRadiusMm + params.wallThicknessMm)) / 0.083f + 0.5f));",
            "  if (height < 4 || height > 80) return false;",
            "  if (params.hoursY + height > 240.0f || params.minutesY + height > 240.0f) return false;",
            "  if (params.hoursY < params.minutesY + height && params.minutesY < params.hoursY + height) return false;",
            "  return true;",
            "}",
            "",
            "inline bool setParam(Params &params, const char *name, float value) {",
            "  if (name == nullptr || !std::isfinite(value)) return false;",
            "  for (std::size_t i = 0; i < FIELD_COUNT; ++i) {",
            "    const Field &field = FIELDS[i];",
            "    if (std::strcmp(name, field.name) != 0) continue;",
            "    Params candidate = params;",
            "    candidate.*(field.member) = value;",
            "    if (!validate(candidate)) return false;",
            "    params = candidate;",
            "    return true;",
            "  }",
            "  return false;",
            "}",
            "",
            "} // namespace physical",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    check = len(sys.argv) == 2 and sys.argv[1] == "--check"
    if len(sys.argv) > 1 and not check:
        print("usage: gen_physical.py [--check]", file=sys.stderr)
        return 2
    try:
        schema, fields, digest = load_schema()
        generated = {
            TS_PATH: generate_ts(schema, fields, digest),
            CPP_PATH: generate_cpp(schema, fields, digest),
        }
        mismatches: list[str] = []
        for path, content in generated.items():
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if check:
                if existing != content:
                    mismatches.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
        if check and mismatches:
            print("generated files are out of date:", ", ".join(mismatches), file=sys.stderr)
            return 1
        if check:
            print("physical schema generated files are up to date")
        else:
            print("wrote", TS_PATH.relative_to(ROOT), "and", CPP_PATH.relative_to(ROOT))
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"gen_physical.py: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
