// GENERATED by sim/tools/gen_material.py — do not edit.
// Source: spec/material-schema.json (schema 1, sha256:c36669ff3b60a58c2b469151de079b832c5b47c651e72ace283d396aa9f0d36d)

import type { Params } from "../params";
import { DEFAULT_PARAMS } from "../params";

export const MATERIAL_VERSION = 1 as const;
export const MATERIAL_SCHEMA_DIGEST = "sha256:c36669ff3b60a58c2b469151de079b832c5b47c651e72ace283d396aa9f0d36d" as const;

/** Physical material, vessel and lighting properties (units and bounds in MATERIAL_META). */
export interface Material {
  ior: number;
  absorptionR: number;
  absorptionG: number;
  absorptionB: number;
  scattering: number;
  emissionR: number;
  emissionG: number;
  emissionB: number;
  metallic: number;
  metalReflectance: number;
  phase: number;
  density: number;
  viscosity: number;
  surfaceTension: number;
  contactAngle: number;
  contactHysteresis: number;
  solidsFraction: number;
  dryingTime: number;
  gasMode: number;
  gasLevel: number;
  bubbleRadius: number;
  foamStability: number;
  innerRadius: number;
  wallThickness: number;
  wallIor: number;
  lightElevation: number;
  lightSize: number;
  lightIntensity: number;
  ambient: number;
  exposure: number;
}

export type MaterialKey = keyof Material;

export interface MaterialFieldMeta {
  readonly key: MaterialKey;
  readonly label: string;
  readonly unit: string;
  readonly min: number;
  readonly max: number;
  readonly step: number;
  readonly group: string;
  readonly help: string;
  readonly integer: boolean;
  /** Slider moves in log space (the range spans decades). */
  readonly log: boolean;
  /** Integer enum labels, options[value - min]. */
  readonly options?: readonly string[];
}

export const DEFAULT_MATERIAL: Material = {
  ior: 1.333,
  absorptionR: 0,
  absorptionG: 0,
  absorptionB: 0,
  scattering: 0,
  emissionR: 0,
  emissionG: 0,
  emissionB: 0,
  metallic: 0,
  metalReflectance: 0.75,
  phase: 0,
  density: 1000,
  viscosity: 1,
  surfaceTension: 72,
  contactAngle: 20,
  contactHysteresis: 10,
  solidsFraction: 0,
  dryingTime: 1,
  gasMode: 0,
  gasLevel: 0.5,
  bubbleRadius: 0.06,
  foamStability: 4,
  innerRadius: 2.25,
  wallThickness: 0.5,
  wallIor: 1.49,
  lightElevation: 60,
  lightSize: 30,
  lightIntensity: 1,
  ambient: 0.2,
  exposure: 1,
};

export const MATERIAL_META: readonly MaterialFieldMeta[] = [
  { key: "ior", label: "Refractive index", unit: "", min: 1, max: 1.8, step: 0.005, group: "Optics", help: "Refractive index of the liquid at 20 °C (water 1.333, olive oil 1.47, honey 1.49, ethanol 1.36). Sets the Fresnel reflections at the wall–liquid interface, the depth warp of marks behind the liquid and the wall specular seen over it.", integer: false, log: false },
  { key: "absorptionR", label: "Absorption red", unit: "1/mm", min: 0, max: 50, step: 0.005, group: "Optics", help: "Absorption coefficient K of the red channel (Beer–Lambert / Kubelka–Munk). 0 = colourless; 0.1/mm tints a 4.5 mm chord to 64 %; 1/mm makes it opaque-dark; whole blood ≈ (1, 20, 25)/mm.", integer: false, log: true },
  { key: "absorptionG", label: "Absorption green", unit: "1/mm", min: 0, max: 50, step: 0.005, group: "Optics", help: "Absorption coefficient K of the green channel.", integer: false, log: true },
  { key: "absorptionB", label: "Absorption blue", unit: "1/mm", min: 0, max: 50, step: 0.005, group: "Optics", help: "Absorption coefficient K of the blue channel.", integer: false, log: true },
  { key: "scattering", label: "Scattering (reduced)", unit: "1/mm", min: 0, max: 50, step: 0.01, group: "Optics", help: "Reduced scattering coefficient S = μs·(1−g) of the bulk (two-flux Kubelka–Munk). 0 = clear; milk ≈ 3/mm, blood ≈ 1/mm (with strong green/blue absorption), ink ≈ 0. Scattering makes the body opaque and Lambert-shaded instead of see-through.", integer: false, log: true },
  { key: "emissionR", label: "Emission red", unit: "radiance", min: 0, max: 1, step: 0.005, group: "Optics", help: "Self-emitted radiance of the liquid, red channel, relative to the diffuse illumination unit (1 = as bright as a white surface under the light). 0 for ordinary liquids; glow sticks, plasma and molten metal are the only emitters.", integer: false, log: false },
  { key: "emissionG", label: "Emission green", unit: "radiance", min: 0, max: 1, step: 0.005, group: "Optics", help: "Self-emitted radiance, green channel.", integer: false, log: false },
  { key: "emissionB", label: "Emission blue", unit: "radiance", min: 0, max: 1, step: 0.005, group: "Optics", help: "Self-emitted radiance, blue channel.", integer: false, log: false },
  { key: "metallic", label: "Metallic", unit: "", min: 0, max: 1, step: 1, group: "Optics", help: "1 = a liquid metal (mercury, molten iron): opaque conductor, mirror specular, no transmission; the absorption and scattering fields are ignored. 0 = dielectric liquid.", integer: true, log: false, options: ["dielectric","metal"] },
  { key: "metalReflectance", label: "Metal reflectance", unit: "", min: 0.2, max: 1, step: 0.01, group: "Optics", help: "Neutral (grey) reflectance of the metal surface; only used when metallic = 1 (mercury 0.75, molten iron 0.3 + emission).", integer: false, log: false },
  { key: "phase", label: "Phase", unit: "", min: 0, max: 1, step: 1, group: "Optics", help: "0 = liquid. 1 = plasma / gas discharge: no inertia, no slug, no meniscus dynamics, no film, no residue, no bubbles; must emit light. Xenon is the reference.", integer: true, log: false, options: ["liquid","plasma"] },
  { key: "density", label: "Density", unit: "kg/m³", min: 1, max: 15000, step: 1, group: "Fluid", help: "Mass density at 20 °C (water 1000, ethanol 789, olive oil 915, honey 1420, mercury 13546, molten iron 7000; a gas/plasma column such as xenon 5.9). Enters the capillary length, the Bond number, the viscous drag coordinate and the bubble rise speed.", integer: false, log: false },
  { key: "viscosity", label: "Dynamic viscosity", unit: "mPa·s", min: 0.05, max: 100000, step: 0.01, group: "Fluid", help: "Dynamic viscosity μ at 20 °C (liquid oxygen 0.19, water 1.0, champagne 1.5, blood 4, olive oil 84, honey 10000). Drives slug drag, end bounce, surface damping, the dynamic contact angle, the trailing film, residue drain-back and bubble rise — all through one number.", integer: false, log: true },
  { key: "surfaceTension", label: "Surface tension", unit: "mN/m", min: 5, max: 2000, step: 0.5, group: "Fluid", help: "Liquid–air surface tension γ at 20 °C (water 72, ethanol 22, olive oil 32, honey ≈ 70, mercury 485, molten iron ≈ 1800). Sets the capillary length √(γ/ρg), the meniscus spring and the capillary number.", integer: false, log: false },
  { key: "contactAngle", label: "Contact angle", unit: "°", min: 0, max: 180, step: 1, group: "Wetting", help: "Static contact angle of the liquid on the vessel wall (water on clean glass 20°, oil on acrylic 15°, mercury on glass 140°). Below 90° the meniscus is concave (wetting), above it a convex bead. The band angle ± hysteresis must not cross 90°.", integer: false, log: false },
  { key: "contactHysteresis", label: "Contact-angle hysteresis", unit: "°", min: 0, max: 30, step: 0.5, group: "Wetting", help: "Half-band of the advancing/receding angles around the static angle: a contact line advances at θ + h and recedes at θ − h (clean glass 5–10°, rough or coated walls 15–25°). Larger hysteresis pins the liquid longer before it moves.", integer: false, log: false },
  { key: "solidsFraction", label: "Non-volatile solids", unit: "", min: 0, max: 1, step: 0.01, group: "Wetting", help: "Fraction of the liquid left on the wall as a stain when its film dries (water 0, wine 0.02, blood 0.45, ink 0.5, honey 0.8). 0 = a receding edge leaves no residue. Only wetting liquids leave residue.", integer: false, log: false },
  { key: "dryingTime", label: "Drying time", unit: "s", min: 0.1, max: 10, step: 0.1, group: "Wetting", help: "Time constant for the wall film to dry into its stain, on the watch's compressed time scale (1 s ≈ a minute of real drying). Tilting drains the film faster.", integer: false, log: false },
  { key: "gasMode", label: "Gas", unit: "", min: 0, max: 3, step: 1, group: "Gas", help: "0 none; 1 dissolved gas (carbonation: a steady rising bead, watery liquids only); 2 boiling (dense fast bubbles, cryogenic liquids); 3 trapped air (slow bubbles held in a medium or viscous liquid: a few to a dense suspension).", integer: true, log: false, options: ["none","dissolved","boiling","trapped"] },
  { key: "gasLevel", label: "Gas level", unit: "", min: 0, max: 1, step: 0.01, group: "Gas", help: "How much gas: nucleation density of the bead (bubble count) within the mode's range.", integer: false, log: false },
  { key: "bubbleRadius", label: "Bubble radius", unit: "mm", min: 0.02, max: 0.4, step: 0.005, group: "Gas", help: "Typical bubble radius (champagne 0.05, beer 0.1, trapped air in honey 0.12). Sets the drawn size and, with viscosity and density, the Stokes rise speed.", integer: false, log: false },
  { key: "foamStability", label: "Foam stability", unit: "s", min: 0, max: 30, step: 0.5, group: "Gas", help: "Mean time a bubble survives at the surface before it pops (pure water < 1 s, beer/champagne 3–5 s, viscous or surfactant-rich liquids 10–30 s). 0 = bubbles vanish at the surface.", integer: false, log: false },
  { key: "innerRadius", label: "Inner radius", unit: "mm", min: 0.5, max: 3, step: 0.05, group: "Vessel", help: "Bore radius of the vessel. Sets every chord length (optical depth), the Bond number, the drag coordinate μ/(ρr²) and the bubble/film scales. The drawn tube height is a separate layout choice (the panel shows the tube through a magnifying rod).", integer: false, log: false },
  { key: "wallThickness", label: "Wall thickness", unit: "mm", min: 0.05, max: 1.5, step: 0.05, group: "Vessel", help: "Glass/acrylic wall thickness: the dark silhouette band of the tube where rays pass through wall only.", integer: false, log: false },
  { key: "wallIor", label: "Wall refractive index", unit: "", min: 1.4, max: 1.6, step: 0.005, group: "Vessel", help: "Refractive index of the vessel wall (acrylic 1.49, borosilicate 1.47, soda-lime 1.52). With the liquid index it sets the interface reflections and the wall specular over the liquid.", integer: false, log: false },
  { key: "lightElevation", label: "Light elevation", unit: "°", min: 0, max: 85, step: 1, group: "Lighting", help: "Angle of the room light above the panel normal in the tube's cross-section. The specular highlight sits at half this angle from the centre row. Used directly for self-lit liquids; ordinary liquids take the world-up light from the IMU.", integer: false, log: false },
  { key: "lightSize", label: "Light size", unit: "°", min: 5, max: 90, step: 1, group: "Lighting", help: "Angular size (FWHM) of the light source: a small lamp 10°, a window 40–60°. Sets the highlight band width and softness.", integer: false, log: false },
  { key: "lightIntensity", label: "Light intensity", unit: "", min: 0, max: 3, step: 0.05, group: "Lighting", help: "Radiance of the light relative to a normal room lamp (1). Sets the specular highlights on liquid and glass and the diffuse illumination of the backing.", integer: false, log: false },
  { key: "ambient", label: "Ambient light", unit: "", min: 0, max: 1, step: 0.01, group: "Lighting", help: "Diffuse environment fill relative to the light: lifts the shaded side of the body and the empty wall, and desaturates bright reflections toward white.", integer: false, log: false },
  { key: "exposure", label: "Exposure", unit: "", min: 0.25, max: 4, step: 0.05, group: "Lighting", help: "Display exposure of the whole scene (art direction, not a material property): scales the illumination before encoding to the panel.", integer: false, log: false },
];

export const MATERIAL_KEYS: readonly MaterialKey[] = ["ior","absorptionR","absorptionG","absorptionB","scattering","emissionR","emissionG","emissionB","metallic","metalReflectance","phase","density","viscosity","surfaceTension","contactAngle","contactHysteresis","solidsFraction","dryingTime","gasMode","gasLevel","bubbleRadius","foamStability","innerRadius","wallThickness","wallIor","lightElevation","lightSize","lightIntensity","ambient","exposure"];

/** Legacy Params keys a material file may set directly (schema design.allow); every other key is derived. */
export const DESIGN_KEYS = [
  "tubeHeight",
  "hoursY",
  "minutesY",
  "remaining",
  "cornerR",
  "lens",
  "lensCurve",
  "meniscusLens",
  "topLens",
  "topParallax",
  "tickDryLens",
  "digitDryLens",
  "tickParallax",
  "digitParallax",
  "tubeBack",
  "tubeBack2",
  "tubeBackGradient",
  "ticksH",
  "tickStepH",
  "tickMajorEveryH",
  "tickMinorHeightH",
  "tickMajorHeightH",
  "tickMinorWidthH",
  "tickMajorWidthH",
  "tickColorH",
  "tickMajorColorH",
  "tickPosH",
  "ticksM",
  "tickStepM",
  "tickMajorEveryM",
  "tickMinorHeightM",
  "tickMajorHeightM",
  "tickMinorWidthM",
  "tickMajorWidthM",
  "tickColorM",
  "tickMajorColorM",
  "tickPosM",
  "ticksOnTop",
  "tickEmboss",
  "digits",
  "digitColor",
  "digitColor2",
  "digitShadow",
  "digitShadowColor",
  "digitShadowStrength",
  "digitShadowOffset",
  "digitTint",
  "digitTintAmount",
  "digitTone",
  "digitFont",
  "digitScaleX",
  "digitScaleY",
  "digitScaleXMin",
  "digitScaleYMin",
  "digitBottomMin",
  "digitBottom",
  "digitsOnTop",
  "digitsLeadingZero",
  "digitMinuteStep",
  "digitHourStep",
  "digitHourStart",
  "digitMinuteStart",
  "digitsLastOnlyH",
  "digitsLastOnlyM",
  "freeLiquid",
  "freeHomeK",
  "readTiltStart",
  "readTiltEnd",
  "playHold",
  "brightness",
  "tickBright",
  "digitBright",
  "markContrast",
  "fizzSizeVar",
  "fizzShadeOff",
  "fizzDepth",
  "fizzBlick",
  "fizzSquash",
  "fizzAcrossGain",
] as const satisfies readonly (keyof Params)[];

export type DesignKey = (typeof DESIGN_KEYS)[number];
export type Design = Partial<Pick<Params, DesignKey>>;

export const MATERIAL_ENVELOPE_KIND = "liquid-watch-material" as const;

/** Where a preset's property value comes from (docs/physical-renderer.md, "Provenance of preset values"). */
export type Provenance = "measured" | "estimated" | "artistic";
export const PROVENANCE_VALUES: readonly Provenance[] = ["measured", "estimated", "artistic"];
export type MaterialProvenance = Partial<Record<MaterialKey, Provenance>>;

/** A material file: the material, the allowlisted design keys and optional name / per-property provenance. */
export interface MaterialEnvelope {
  readonly kind: typeof MATERIAL_ENVELOPE_KIND;
  readonly version: typeof MATERIAL_VERSION;
  readonly name?: string;
  readonly material: Material;
  readonly design: Design;
  readonly provenance?: MaterialProvenance;
}

const ENVELOPE_KEYS: readonly string[] = ["kind", "version", "name", "material", "design", "provenance"];
const HEX_COLOUR = /^#[0-9a-f]{6}$/i;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key);
}

function isMaterialKey(key: string): key is MaterialKey {
  return (MATERIAL_KEYS as readonly string[]).includes(key);
}

function isDesignKey(key: string): key is DesignKey {
  return (DESIGN_KEYS as readonly string[]).includes(key);
}

function fail(what: string, message: string): never {
  throw new Error(`Invalid ${what}: ${message}`);
}

/** Validate a complete material: exactly the schema's keys, each finite, in range and integer where flagged. */
export function validateMaterial(value: unknown): Material {
  if (!isRecord(value)) fail("material", "expected an object");
  const unknown = Object.keys(value).filter((key) => !isMaterialKey(key));
  if (unknown.length) fail("material", `unknown field(s) ${unknown.join(", ")}`);
  const result = {} as Material;
  for (const meta of MATERIAL_META) {
    if (!hasOwn(value, meta.key)) fail("material", `missing field ${meta.key}`);
    const raw = value[meta.key];
    if (typeof raw !== "number" || !Number.isFinite(raw)) fail("material", `${meta.key} must be a finite number`);
    if (raw < meta.min || raw > meta.max) fail("material", `${meta.key} = ${raw} must be in [${meta.min}, ${meta.max}]`);
    if (meta.integer && !Number.isInteger(raw)) fail("material", `${meta.key} = ${raw} must be an integer`);
    result[meta.key] = raw;
  }
  return result;
}

/** Validate a (partial) design: only allowlisted Params keys, each of its Params type; strings are #rrggbb colours. */
export function validateDesign(value: unknown): Design {
  if (!isRecord(value)) fail("design", "expected an object");
  const bad = Object.keys(value).filter((key) => !isDesignKey(key));
  if (bad.length) fail("design", `key(s) not in the design allowlist (derived from the material or fixed): ${bad.join(", ")}`);
  const result: Record<string, unknown> = {};
  for (const key of DESIGN_KEYS) {
    if (!hasOwn(value, key)) continue;
    const raw = value[key];
    const want = typeof DEFAULT_PARAMS[key];
    if (typeof raw !== want) fail("design", `${key} must be a ${want}`);
    if (typeof raw === "number" && !Number.isFinite(raw)) fail("design", `${key} must be finite`);
    if (typeof raw === "string" && !HEX_COLOUR.test(raw)) fail("design", `${key} = ${JSON.stringify(raw)} must be a #rrggbb colour`);
    result[key] = raw;
  }
  return result as Design;
}

function validateProvenance(value: unknown): MaterialProvenance {
  if (!isRecord(value)) fail("provenance", "expected an object");
  const result: MaterialProvenance = {};
  const unknown = Object.keys(value).filter((key) => !isMaterialKey(key));
  if (unknown.length) fail("provenance", `unknown material field(s) ${unknown.join(", ")}`);
  for (const key of MATERIAL_KEYS) {
    if (!hasOwn(value, key)) continue;
    const raw = value[key];
    if (!(PROVENANCE_VALUES as readonly unknown[]).includes(raw)) fail("provenance", `${key} must be one of ${PROVENANCE_VALUES.join(", ")}`);
    result[key] = raw as Provenance;
  }
  return result;
}

/** Copy of an object with only the keys `keep` accepts; for explicit migration steps only. */
export function keepKeys(value: unknown, keep: (key: string) => boolean): unknown {
  if (!isRecord(value)) return value;
  const result: Record<string, unknown> = {};
  for (const key of Object.keys(value)) if (keep(key)) result[key] = value[key];
  return result;
}

/**
 * Bring a material envelope of any supported version to MATERIAL_VERSION, unvalidated. Each `case`
 * upgrades one version in place; a key is dropped only by the explicit step of the version that removed
 * it. A current-version file is passed through untouched, so the strict validators reject any key the
 * schema does not know (envelope, material, provenance) instead of losing it silently.
 */
export function migrateMaterial(o: Record<string, unknown>): Record<string, unknown> {
  const from = o.version;
  if (typeof from !== "number" || !Number.isInteger(from) || from < 1) fail("material file", `unsupported version ${JSON.stringify(from)}`);
  if (from > MATERIAL_VERSION) fail("material file", `version ${from} is newer than this simulator (${MATERIAL_VERSION})`);
  const r: Record<string, unknown> = { ...o };
  if (isRecord(r.material)) r.material = { ...r.material };
  for (let v = from; v < MATERIAL_VERSION; v++) {
    switch (v) {
      // case 1: // version 1 → 2: rename / convert r.material fields, and drop the keys version 2 removed:
      //   r.material = keepKeys(r.material, (key) => key !== "removedInV2");
      //   if (hasOwn(r, "provenance")) r.provenance = keepKeys(r.provenance, (key) => key !== "removedInV2");
      //   break;
      default:
        fail("material file", `no migration from version ${v}`);
    }
  }
  r.version = MATERIAL_VERSION;
  return r;
}

/** Parse and validate a material file (JSON text or an already parsed object). Legacy Params exports are rejected. */
export function parseMaterialEnvelope(input: unknown): MaterialEnvelope {
  let value = input;
  if (typeof input === "string") {
    try { value = JSON.parse(input); } catch (error) { fail("material file", `not JSON (${(error as Error).message})`); }
  }
  if (!isRecord(value)) fail("material file", "expected a JSON object");
  if (hasOwn(value, "v") && hasOwn(value, "liquid")) {
    throw new Error("This is a legacy Params export (it has `v` and `liquid`), not a material file; legacy configs are rejected.");
  }
  if (value.kind !== MATERIAL_ENVELOPE_KIND) fail("material file", `kind must be "${MATERIAL_ENVELOPE_KIND}" (got ${JSON.stringify(value.kind)})`);
  const o = migrateMaterial(value);
  const unknown = Object.keys(o).filter((key) => !ENVELOPE_KEYS.includes(key));
  if (unknown.length) fail("material file", `unknown field(s) ${unknown.join(", ")}`);
  if (hasOwn(o, "name") && typeof o.name !== "string") fail("material file", "name must be a string");
  return {
    kind: MATERIAL_ENVELOPE_KIND,
    version: MATERIAL_VERSION,
    ...(typeof o.name === "string" ? { name: o.name } : {}),
    material: validateMaterial(o.material),
    design: validateDesign(o.design),
    ...(hasOwn(o, "provenance") ? { provenance: validateProvenance(o.provenance) } : {}),
  };
}

/** Validate and write a material file: canonical key order, 2-space JSON, trailing newline. */
export function serializeMaterialEnvelope(env: { material: Material; design: Design; name?: string; provenance?: MaterialProvenance }): string {
  const parsed = parseMaterialEnvelope({ ...env, kind: MATERIAL_ENVELOPE_KIND, version: MATERIAL_VERSION });
  return JSON.stringify(parsed, null, 2) + "\n";
}
